# Generated by Django 2.1.7 on 2019-04-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20190415_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='time_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
