# Generated by Django 2.1.7 on 2019-04-15 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20190415_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='time_modified',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
