# Generated by Django 2.1.7 on 2019-04-11 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20190411_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='day_name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
