# Generated by Django 2.1.7 on 2019-04-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20190411_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
