# Generated by Django 2.1.7 on 2019-04-15 17:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_info_time_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
