# Generated by Django 2.1.7 on 2019-04-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20190415_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='time_modified',
            field=models.DateTimeField(),
        ),
    ]
