# Generated by Django 2.2.4 on 2019-08-24 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_auto_20190415_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='info',
            name='workout',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='day',
        ),
        migrations.DeleteModel(
            name='day',
        ),
        migrations.DeleteModel(
            name='info',
        ),
        migrations.DeleteModel(
            name='workout',
        ),
    ]
